apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-ui
  name: edgex-ui
  namespace: edgex
spec:
  ports:
  - name: http
    nodePort: 32176
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    org.edgexfoundry.service: edgex-ui
  type: NodePort
