apiVersion: v1
kind: Pod
metadata:
  name: edgex-nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /etc/nginx/conf.d/
        name: nginx-conf
        readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
        items:
          - key: default
            path: default.conf
