---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-sidecar-injector
  namespace: kube-system
imagePullSecrets:
  - name: k8s-sidecar-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: k8s-sidecar-injector
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-sidecar-injector
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: k8s-sidecar-injector
  namespace: kube-system
roleRef:
  kind: Role
  name: k8s-sidecar-injector
  apiGroup: rbac.authorization.k8s.io
