apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - image: mindovermiles262/ktunnel:0.1.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: debug
    volumeMounts:
      - mountPath: /root/.kube
        name: kubeconfig
        readOnly: true
  restartPolicy: Never
  volumes:
    - name: kubeconfig
      secret:
        secretName: kubeconfig
