---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ktunnel-config
  namespace: kube-system
  labels:
    com.ibbproject/app: ibb-ktunnel-sidecar-injector
data:
  ibb-ktunnel.conf: |
    name: ibb-ktunnel
    containers:
    - name: ktunnel
      image: us-central1-docker.pkg.dev/padi-staging/public/ibb-ktunnel:latest
			volumeMounts:
				- mountPath: /root/.kube/
					name: kubeconfig
					readOnly: true
				- mountPath: /etc/podinfo
					name: podinfo

