apiVersion: v1
kind: Pod
metadata:
  name: injector-debug
  annotations:
    injector.ktunnel.ibbproject.com/request: ibb-ktunnel
spec:
  containers:
  # - image: debian:jessie
  #   command:
  #     - sleep
  #     - "3600"
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: debian
  restartPolicy: Never
