#
# This is a debug pod. It is used to test whether or not you have properly
# configured the sidecar injector. When you `kubectl apply -f debug-pod.yaml`,
# you should see 2 containers if the sidecar injector is properly working.
#
---
apiVersion: v1
kind: Pod
metadata:
  name: injector-debug
  labels:
    injector.ktunnel.ibbproject.com/id: "aduss-03"
    injector.ktunnel.ibbproject.com/port: "8080"
  annotations:
    injector.ktunnel.ibbproject.com/request: ibb-ktunnel
spec:
  containers:
  - image: us-central1-docker.pkg.dev/padi-staging/public/nginx-8080:v1.1.0
    name: nginx
    imagePullPolicy: IfNotPresent
  restartPolicy: Never
  volumes:
    - name: kubeconfig
      secret:
        secretName: kubeconfig
    - name: podinfo
      downwardAPI:
        items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations

