apiVersion: v1
kind: Pod
metadata:
  name: injector-debug
  annotations:
    injector.ktunnel.ibbproject.com/request: ibb-ktunnel
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Never

